language: go
go:
  - 1.4
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq libgles2-mesa-dev
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - go get golang.org/x/tools/cmd/vet
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d ./)
  - go tool vet -composites=false -unsafeptr=false ./
  - go test -v -race ./...
